### ISSUE TITLE
Cadastros de pessoa

### ISSUE THREAD

**Issue by jefsterjr** [jefsterjr/spring#1]
Crie um caso de uso de cadastro de pessoa.
Pessoa terá os atributos:
-  id
- nome 
- idade, 
- endereço(Apenas um campo String para isso) 
- telefone (Campo String)

Crie endpoints para: 

- consultar uma pessoa pelo ID 
- consultar todas as pessoas 
- inserir
- alterar 
- excluir

**Comment by silvioalexandreos** [comment]
Concluído

**Comment by silvioalexandreos** [comment]
Concluído
